# Generated by Django 5.0.1 on 2024-11-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline", "0002_milestone_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="milestone",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="milestone",
            name="future",
            field=models.BooleanField(default=False),
        ),
    ]
